from typing import Optional
from pydantic import BaseModel, EmailStr, Field


class VerifyTokenRequest(BaseModel):
    """Payload to verify an ID token generated by Firebase Authentication."""

    token: str = Field(..., description="Firebase ID token string")


class CreateUserRequest(BaseModel):
    """Payload to programmatically create a user in Firebase Auth and database."""

    email: EmailStr = Field(..., description="Email address for the new user profile")
    display_name: Optional[str] = Field(None, description="Optional public name of the user")
